version: "3.9"

services:
  postgres:
    profiles:
      - docker-db

  service-discovery:
    depends_on: []

  common:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/frotas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_HIKARI_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/frotas
    depends_on:
      service-discovery:
        condition: service_started

  efrotas-api:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/frotas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_HIKARI_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/frotas
    depends_on:
      - common

  erh-api:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/frotas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_ERH_URL: jdbc:postgresql://host.docker.internal:5432/erh
      SPRING_DATASOURCE_ERH_USERNAME: postgres
      SPRING_DATASOURCE_ERH_PASSWORD: postgres
      SPRING_DATASOURCE_HIKARI_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/frotas
      SPRING_DATASOURCE_ERH_HIKARI_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/erh
    depends_on:
      - common
